services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      sh -c "python setup.py sdist"
      sh -c "pip3 install diploma-frontend/dist/diploma-frontend-0.6.tar.gz"