# Generated by Django 3.2.16 on 2023-06-13 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user_profile.models.profile_avatar_directory_path, verbose_name='аватар')),
                ('alt_text', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Аватарки',
                'verbose_name_plural': 'Аватарки',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='телефон')),
                ('avatar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_profile.image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
