# Generated by Django 3.2.16 on 2023-06-12 14:00

from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user_profile.models.profile_avatar_directory_path, verbose_name='аватар')),
                ('alt_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_profile.image'),
        ),
    ]
