# Generated by Django 3.2.16 on 2023-06-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20230612_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_profile.image'),
        ),
    ]
