# Generated by Django 3.2.16 on 2023-06-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_avatar'),
        ('user_profile', '0004_alter_profile_avatar'),
    ]

    operations = [
    ]
